Добавляет функционал фильмов и пользователей
Seetochka/java-filmorate pull request #1
Opened 2022-04-20 18:02 UTC by Seetochka

2022-04-20 19:06 UTC, eugene-lenkevich requested changes
Привет, Светлана , спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-04-20 19:06 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private Map<Integer, User> users = new HashMap<>();
Кстати, тут лучше подойдет ConcurrentHashMap. Этого нет в курсе, но тем не менее 
Вэб - это стопроцентная многопоточная среда :)
PS это FYI

https://habr.com/ru/post/132884/

2022-04-21 17:22 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ModelNotFoundException.java
> +public class ModelNotFoundException extends RuntimeException {
Не знаю что на меня нашло что сделала непроверяемое(
Исправила

2022-04-21 17:35 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private Map<Integer, User> users = new HashMap<>();
Почитала, спасибо за инфу)
Заменила

2022-04-21 18:09 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-04-22 06:17 UTC, merged