Add reviews
Seetochka/java-filmorate pull request #13
Opened 2022-06-08 22:15 UTC by heck99

2022-06-11 13:55 UTC, Seetochka requested changes
В общем все хорошо, по самим файлам в некоторых местах есть лишние строки, где-то не хватает пробелов. В конце каждого файла должна быть одна пустая строка, не должно быть больше одной пустой строки, это надо будет поправить руками, а для потерянных пробелов есть _Выделить все_ и _Option+Command+L_ или _Alt+Ctrl+L_

2022-06-11 13:55 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +    public Collection<Review> findAllByFilmId(@RequestParam(defaultValue = "10", required = false) Integer count,
**todo:** в ТЗ они в другом порядке идут

2022-06-11 13:55 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +                                              @RequestParam(required = false) Integer filmId)
**question:** зачем давать возможность идти дальше без id фильма, если по названию метода все зависит от него

2022-06-11 13:55 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +    public void deleteReview(@PathVariable("id") int reviewID) throws ModelNotFoundException {
**typo:** нужно `reviewId` здесь и ниже

2022-06-11 13:55 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +    public ReviewService(ReviewStorage storage, FilmService filmService,
**todo:** давай сделаем через аннотации
[@RequiredArgsConstructor](https://www.baeldung.com/spring-injection-lombok#constructor-injection-with-lombok) очень удобно, когда только одна реализация интерфейса

2022-06-11 13:55 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        return storage.findAll(count);
**question:** зачем получать все, если название метода говорит что мы получим по конкретному фильму

2022-06-11 13:55 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +
**todo:** пустые строки не нужны

2022-06-11 13:55 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/storage/rewie/ReviewDbStorage.java
> +package ru.yandex.practicum.filmorate.storage.rewie;
**typo:** пропустил последнюю букву в названии пакета

2022-06-13 14:21 UTC, heck99 commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        return storage.findAll(count);
По ТЗ сказано, что если ID не указан, то нужно получить всё
![image](https://user-images.githubusercontent.com/83956660/173375250-e180fae1-138e-4930-8ec2-d78b50008492.png)

2022-06-13 20:54 UTC, RobinsonKrusoe approved these changes
Меня, как даже, не джуна, всё устравивает.)

2022-06-14 04:20 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        return storage.findAll(count);
Ок

2022-06-14 04:21 UTC, Seetochka approved these changes

2022-06-14 04:23 UTC, merged