Add search
Seetochka/java-filmorate pull request #15
Opened 2022-06-10 08:42 UTC by EvgeniyaKuzmina

2022-06-10 13:26 UTC, heck99 commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +            return jdbcTemplate.query(sqlAllDirectors, (rs, rowNum) -> makeDirector(rs, jdbcTemplate));
да, вот так должен выглядеть метод стоража создали запрос и выполнили, все обработки в сервис

2022-06-10 13:26 UTC, heck99 commented on src/main/java/ru/yandex/practicum/filmorate/services/DirectorService.java
> +       return directorDbStorage.updateDirector(director);
лучше вот тут проверить есть ли такой DIrector
просто вызвав getDirectorById, если придёт Optional.empty то кидаем ModelNotFound

2022-06-10 13:26 UTC, heck99 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (directorId == null) {
а зачем ты делаешь проверку на null? 
Если тебе нужно, чтобы поле было обязательно заполнено убери required = false

2022-06-10 13:26 UTC, heck99 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            return service.getFilmsByDirector(Long.parseLong(directorId), sortBy);
да в сервисе всё получится, а если не получится, он сам должен кинуть исключение, которое не нужно ловить 
в идеале у тебя в контроллере метод должен просто отдавать данные сервису, а уже сервис делает все проверки и т.п.

2022-06-10 13:26 UTC, heck99 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/DirectorController.java
> +        try {
не стоит ничего тут ловить,

2022-06-10 13:26 UTC, heck99 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/DirectorController.java
> +        return directorService.getAllDirectors();
вот так просто вызов метода и всё больше контроллер ничего не должен
Его ответственность поймать запрос и передать его дальше

2022-06-10 14:22 UTC, heck99 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/DirectorController.java
> +    @PutMapping(value = {"/{id}"})
тут немного изменилось и тепрь в пути не должно быть id

2022-06-11 13:01 UTC, Seetochka requested changes
Общее замечание - нужно сделать все в стиле проекта, именование методов save, delete и find, а не create, remove и get, комментарии методов через /** */, у удалять лишние импорты, если хочешь можем созвониться, я покажу как можно удобно готовить ветку к коммиту

2022-06-13 13:12 UTC, heck99 requested changes

2022-06-13 13:12 UTC, heck99 commented on src/main/java/ru/yandex/practicum/filmorate/services/DirectorService.java
> +        if (!filmsWithDirector.isEmpty()) {
praise: очень круто, что ты выбрала именно такой вариант, еслесть желание сделать идеально, то можешь создать своё исключение в котором будет поле с массивом id, в который будут класться id всех фильмов, где указан твой режиссёр. Потому что сейчас фронту придётся парсить строку, а это не самое приятное занятие, а если у тебя будет поле ids = [массив id], то фронт тебе точно скажет большое спассбо

2022-06-13 13:12 UTC, heck99 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Collection<Film> getFilmsByDirector(@PathVariable String directorId,
todo: Вот тут ты зачем получаешь String directorId исправь на int String directorId и не нужно будет нигде думать, а если кто-то захочет передать туда не число, сам дурак, он просто не найдёт этот эндпоинт или спринг кинет ему exception

2022-06-13 13:12 UTC, heck99 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/DirectorController.java
> +    public Director findDirectorById(@PathVariable String id) throws ModelNotFoundException {
todo: тоже переделай в intid
ты же когда в тело должны передать какой-то объект не рассчитываешь, что туда передадут, что-то не то. Т.е. ты не парсишь сама строку ты говоришь, что там лежит @Valid @RequestBody Director director, а если что-то не то, то я не виновата

2022-06-13 13:12 UTC, heck99 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/DirectorController.java
> +    public String deleteDirector(@PathVariable(required = false) String id) throws ModelNotFoundException, IncorrectParameterException, ValidationException {
todo: тоже замени строку на число, а ещё почему у тебя required = false, если id не придёт, то ты не сможешь удалить режиссёра, поэтому тебе нужно, чтобы он обязательно был

2022-06-14 08:35 UTC, heck99 requested changes
Всё хорошо поправь только в одном месте

2022-06-14 08:35 UTC, heck99 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/DirectorController.java
> +    public void deleteDirector(@PathVariable(required = false) int id) throws ModelNotFoundException, ValidationException {
todo: нужно убрать required = false

2022-06-14 08:36 UTC, heck99 approved these changes
Ты молодец!)

2022-06-14 16:58 UTC, Seetochka approved these changes
Кроме тех моментов по форматированию все отлично, спасибо)

2022-06-14 16:58 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (film.getDirectors() != null) {
**question:** почему одно и то же здесь и на 138 строке?

2022-06-14 16:58 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +            log.warn("updateDirector. {}", message);
**todo:** давай во всех методах кроме `...ById` сдалаем `log.error`

2022-06-14 16:58 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    // поиск фильма по содержащейся строке в названии фильма или в имени режиссёра
**todo:** Здесь забыла комментарий в `/** */` взять или можно вовсе убрать, если у других методов нет

2022-06-14 17:23 UTC, merged