Сдача проекта
Seetochka/java-filmorate pull request #22
Opened 2022-06-15 16:49 UTC by Seetochka

Реализованы функциональности:
- Общие фильмы
- Рекомендации
- Лента событий
- Отзывы
- Поиск

Реализованы фичи:
- Вывод самых популярных фильмов по жанру и годам
- Удаление фильмов и пользователей
- Добавление режиссёров в фильмы

2022-06-15 18:13 UTC, eugene-lenkevich requested changes
Привет, Светлана, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-06-15 18:13 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/event/EventDBStorage.java
> +@Repository
А вот DirectorDbStorage имеет аннотацию @Component :)

PS не уверен про уместность именно аннотации @Repository, она относится к Spring Data и имеет особенности, в частности может трактоваться как JPA-репозиторий, а это не так. Но это не точно, повод задуматься, хотя в данном случае все работать будет, fyi

Русской доки не нашел)

![image](https://user-images.githubusercontent.com/94845100/173895282-ab6475a5-aa78-49e6-bd62-a76624550270.png)

2022-06-15 18:58 UTC, heck99 commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        if (id.isPresent()) {
Если в данном методе использовать лямбду, то в выражении нужно выполнить 2 действия: 
1. проверить, что пользователь с таким id существует вызовом filmService.findById(id.get());, но этот метод выкидывает исключение(исключение проверяемое, поэтому оно требует обязательной проверки внутри лямбды, а мне нужно, чтобы если возникло исключение он просто прокинул его вверх(в сигнатуре метода указано, что метод выкидывает исключение
2. вызвать метод и вернуть значение, которое он вернёт с помощью return storage.findByFilmId(id.get(), count);
как я понимаю в лямбде вообще нельзя использовать return
Можно было бы передавать обёртку Integer id в метод и просто проверять if(!id == null), но так пользователям этого метода будет неочевидно, что передача null это нормальное поведение метода, поэтому я использовал именно Optional

2022-06-15 19:17 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/services/DirectorService.java
> +        findDirectorById(director.getId());
Метод `findDirectorById` уже внутри себя проверяет наличие режиссера, и если его нет выбрасывает `ModelNotFoundException`, который обрабатывается в `ErrorHandler`

2022-06-16 02:53 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/services/DirectorService.java
> +        findDirectorById(director.getId());
Имею в виду здесь director.getId(), это еще до findDirectorById  :)

2022-06-16 02:57 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        if (id.isPresent()) {
Понял, в этом случае все верно, из лямбды так просто не выкинешь исключение, текущий функциональный интерфейс нас в это ограничивает :)

2022-06-16 03:08 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        if (status.isPresent()) {
Тут как минимум дублирование кода - два кусочка кода отличаются только тем что в одном случае идет +2, а в другом +1, далее value == status.get(), то есть внутренний if не нужен во втором случае :)
В общем тут дело не в Optional, от него вообще можно избавиться - например методом orElse(...)

2022-06-16 08:27 UTC, heck99 commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        if (status.isPresent()) {
Второй ты проверяет же, что статус false, а не то, что он есть, я понял, что можно заменить status.get() на value, но от ИФА не избавиться, потому что если лайк уже стоит, то мы не должны ставить ещё один

2022-06-16 08:58 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        if (status.isPresent()) {
На самом деле тут хотелось бы просто избавиться от нагромождения вложенных if-ов и optional-ов, всего то, а как именно не суть важно :)

2022-06-16 15:35 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return null;
Удалили реализацию InMemory

2022-06-16 15:35 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/storage/event/EventDBStorage.java
> +@Repository
Исправили

2022-06-16 15:46 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        if (status.isPresent()) {
Исправили

2022-06-16 15:46 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        if (status.isPresent()) {
Исправили

2022-06-16 16:04 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/constants/Constant.java
> +public class Constant {
Исправили

2022-06-16 16:36 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

PS как мне кажется немаловажный момент заключается в том, чтобы у команды формировался свой единый стиль. Это очень упрощает сопровождение проекта. В дальнейшем команды будут меняться, через какое то время не останется никого, кто начинал проект, но, за счет того что все в принципе сделано единообразно, будет гораздо проще потом во всем разбираться в отличие  от того, если бы разные куски кода были выполнены в разном стиле (но это конечно не  серебряная пуля, а лишь один из множества моментов  =).

2022-07-28 12:52 UTC, merged