Добавляет модель базы данных
Seetochka/java-filmorate pull request #3
Opened 2022-05-15 15:57 UTC by Seetochka

2022-05-15 17:15 UTC, eugene-lenkevich requested changes
Привет, , спасибо за присланное решение

В целом все супер :)
Есть одно совсем небольшое замечание: путь все же имена таблиц будут в единственном числе :)

2022-05-15 17:15 UTC, eugene-lenkevich commented on README.md
> +SELECT f.id,
В этом запросе в group by только одно поле, а в select несколько. Я на глаз, конечно, не определю, но, возможно , в зависимости от диалекта ДБ, он может не отработать :)

2022-05-15 17:15 UTC, eugene-lenkevich commented on README.md
> +https://dbdiagram.io/d/6280dc607f945876b61e9962
А давай все таки сделаем названия таблиц "имя существительное в единственном числе" :)

2022-05-16 06:13 UTC, Seetochka commented on README.md
> +https://dbdiagram.io/d/6280dc607f945876b61e9962
Почему в единственном числе? На проектах встречала только во множественном

2022-05-16 17:57 UTC, Seetochka commented on README.md
> +https://dbdiagram.io/d/6280dc607f945876b61e9962
Исправила

2022-05-16 18:30 UTC, Seetochka commented on README.md
> +SELECT f.id,
Протестировала на БД что была в наличии (MySQL) похожий запрос, выполнился корректно
```
SELECT u.id, u.name, COUNT(f.id_product) AS count_favorites
FROM users u
LEFT JOIN favorites f ON f.id_user = u.id
GROUP BY f.id_product
ORDER BY count_favorites DESC
LIMIT 10
```

2022-05-17 04:32 UTC, eugene-lenkevich commented on README.md
> +SELECT f.id,
Ну ок :)

2022-05-17 04:33 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-05-28 07:31 UTC, merged