Add database
Seetochka/java-filmorate pull request #4
Opened 2022-06-05 09:58 UTC by Seetochka

2022-06-05 18:03 UTC, eugene-lenkevich requested changes
Привет, Светлана , спасибо за PR

Все очень круто :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-06-05 18:03 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +        if (user.isEmpty()) {
Раз уж используешь Optional, то лучше будет использовать весь доступный инструментарий, конкретно здесь поможет orElseThrow :)

https://github.com/qcha/JBook/blob/master/start/optional.md#orelsethrow

2022-06-05 18:03 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public FilmDbStorage(JdbcTemplate jdbcTemplate) {
Можно не задавать руками конструктор, можно добавить аннотацию lombok @RequiredArgsConstroctor

2022-06-05 20:14 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +        if (user.isEmpty()) {
Спасибо, почитала, заменила

2022-06-05 20:15 UTC, Seetochka commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public FilmDbStorage(JdbcTemplate jdbcTemplate) {
Здесь тоже заменила

2022-06-06 03:04 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-06-06 16:57 UTC, merged